name: Keep Render Backend Alive

on:
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes
  workflow_dispatch: # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render backend
        run: curl -s https://freight-tracker.onrender.com/api/shipments
